ALTER TABLE users
  ADD COLUMN IF NOT EXISTS middle_name VARCHAR(60),
  ADD COLUMN IF NOT EXISTS last_name_1 VARCHAR(60),
  ADD COLUMN IF NOT EXISTS last_name_2 VARCHAR(60),
  ADD COLUMN IF NOT EXISTS institutional_email VARCHAR(150),
  ADD COLUMN IF NOT EXISTS address VARCHAR(255),
  ADD COLUMN IF NOT EXISTS start_date DATE,
  ADD COLUMN IF NOT EXISTS end_date DATE,
  ADD COLUMN IF NOT EXISTS group_id INTEGER REFERENCES groups(group_id);
